"""empty message

Revision ID: 55cea86b0bfc
Revises: 72b3e619d2ea
Create Date: 2024-10-03 15:38:07.796362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cea86b0bfc'
down_revision = '72b3e619d2ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###