"""empty message

Revision ID: 72b3e619d2ea
Revises: 1f4d9b868b13
Create Date: 2024-10-03 14:14:15.106364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72b3e619d2ea'
down_revision = '1f4d9b868b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'tax_amount',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'tax_amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###